[tox]
envlist = py310, py311, py312, py313, py314, lint, docs


{%- if cookiecutter.ci_provider == 'Travis CI' %}
[travis]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
{%- endif %}

{%- if cookiecutter.ci_provider == 'Github Actions' %}
[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
{%- endif %}

[testenv]
passenv = CI,TRAVIS,TRAVIS_*
setenv =
    PYTHONPATH = {toxinidir}
extras = test
commands =
    /usr/bin/env make test

[testenv:lint]
skipsdist = true
extras = dev
commands =
    /usr/bin/env make lint

[testenv:docs]
skipsdist = true
extras = dev
commands =
    /usr/bin/env make docs